### ISSUE TITLE
Lack of license information

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-XSLT#3]
As far as i can see, there's no information currently on the copyright licensing of these transformations. I would like to have mine explicitly released under a free license, and wondered which you thought would be appropriate.

**Comment by aidinfolabs** [comment]
Good point. We should apply an open license to the whole collection. I'm not sure what would be appropriate - so if you have any suggestions please do share. Otherwise I'll try and find someone next week at the Open Knowledge Festival who can advise...

**Comment by Bjwebb** [comment]
In my mind, XSLT transforms are basically software - so either GPL if we want copyleft, or a permissive license like the MIT license. I think a more permissive license may actually be useful, since it helps make it as easy as possible to start doing stuff with IATI data.

**Comment by timgdavies** [comment]
Shall we go for MIT?

I assume we just need to add a license.txt to the root - as it is mainly
you and I who have code in there?

Tim

On Thu, Sep 13, 2012 at 1:02 PM, Ben Webb notifications@github.com wrote:

> In my mind, XSLT transforms are basically software - so either GPL if we
> want copyleft, or a permissive license like the MIT license. I think a more
> permissive license may actually be useful, since it helps make it as easy
> as possible to start doing stuff with IATI data.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aidinfolabs/IATI-XSLT/issues/3#issuecomment-8524783.

## 

+44 (0)7834 856 303
@timdavies
http://www.timdavies.org.uk

**Comment by Bjwebb** [comment]
I would be cautious about that 'mainly'. I don't know how many other people have submitted patches etc., but it's probably the correct thing to contact them also.

**Comment by ghost** [comment]
Hello I don't know why I'm reciting notifications about issues on this repo. I have no idea what this is. Have you added the wrong person per chance?
